# Site settings
author: Alyssa Yesilyurt
title: Introduction to Programming
header-img: img/home-bg.png
email: alyssa.yesilyurt@gmail.com
copyright_name: Alyssa Yesilyurt
description: > # this means to ignore newlines until "baseurl:"
  Programming
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alyssa001

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
